### PR TITLE
[#16] Star Wars logo

### PR DESCRIPTION
**Pull request by mfrydrychowicz**
@GoraJakub | @budnickip Please review.

To be discussed: 
I don't know if adding css in this manner is ok. If we gonna use sass and bundle scss together to css file then I need help with that.

Note:
For this part I don't see a need to create react like behaviour because the element is static

### CODE REVIEW

**Comment by mfrydrychowicz** [comment]
@skwirowski it would be nice if you could take a look if this non-react-like approach is also ok

**Comment by budnickip** [comment]
You have to import gameHeader.css in App.css and delete from index.html <link rel="stylesheet" href="styles/components/gameHeader.css"/>
For example like this: @import './components/gameHeader.css';

**Review by budnickip — COMMENTED** [review]
You have to import gameHeader.css in App.css and delete from index.html line 9.
For example like this: @import './components/gameHeader.css';
If we're going to use scss in our project, we should name all style files with .scss

**Comment by mfrydrychowicz** [comment]
> 
> 
> You have to import gameHeader.css in App.css and delete from index.html line 9.
> For example like this: @import './components/gameHeader.css';
> If we're going to use scss in our project, we should name all style files with .scss

@budnickip done

**Review by GoraJakub — APPROVED** [review]
Everything is fine now.

**Pull request merged**
